apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: speedtest-ingress
  namespace: speedtest
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - {{ .Values.domain_name }}
      secretName: cert-tls
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: speedtest
                port:
                  number: 8082
